/*
ISA

instr > imm? > src? > dest?

def name > [value]      --def sixteen 0x10

//Basic Math/Manipulation
MOV -> MOV SRC DEST -> MOVES SOURCE TO DESTINATION
ADD -> ADD SRC DEST -> ADDS SOURCE TO DESTINATION
SUB -> SUB SRC DEST -> SUBTRACTS SOURCE FROM DESTINATION
INC -> INC DEST -> INCREMENTS DESTINATION
DEC -> DEC DEST -> DECREMENTS DESTINATION
MUL -> MUL SRC DEST -> MULTIPLIES DEST BY SOURCE
DIV -> DIV SRC DEST -> DIVIDES DEST BY SOURCE (INTEGER DIVISION)
MOD -> MOD SRC DEST -> DESTINATION SET TO MODULUS OF DEST BY SRC

//Logical/Binary ops
AND -> AND SRC DEST -> DEST = SRC && DEST
OR -> OR SRC DEST -> DEST = SRC || DEST
XOR -> XOR SRC DEST -> DEST = SRC ^ DEST
NOT -> NOT SRC DEST -> DEST = !SRC
SHL -> SHL SRC DEST -> SHIFTS LEFT DEST BY SRC
SHR -> SHR SRC DEST -> SHIFTS RIGHT DEST BY SRC

//Jumps
CMP -> CMP SRC DEST -> SETS CARRY FLAG TO 1 IF SRC AND DEST ARE EQUAL
JG -> JMP ADDRESS SRC DEST
JL
JZ
JMP

//Subroutines/program
CALL
RET
HLT

//Memory Management
PUSH
POP
READ
WRTE

*/


//High level version instructions (non bytecode)
pub enum Instruction {

}